import { cn } from '@/lib/utils';

/*
 * Minimal textarea primitive in the shadcn idiom (Phase C Slice 1, Segment B —
 * no textarea was generated by shadcn init; the wizard description field needs
 * one). Plain element + token-driven classes, mirroring input.tsx styling.
 */
function Textarea({
  className,
  ...props
}: React.ComponentProps<'textarea'>) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
        // Паддинги/размер текста выровнены с канонным Input (аудит 2026-07-12)
        'flex min-h-20 w-full rounded-[10px] border border-input bg-background px-4 py-3 text-base shadow-xs transition-colors outline-none placeholder:text-figma-text-grey focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20',
        className,
      )}
      {...props}
    />
  );
}

export { Textarea };
