#!/bin/bash
# Build iOS release for TestFlight
# Usage: ./build_ios.sh
# Then open Xcode: Product → Archive → Upload to App Store Connect

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SECRETS_FILE="$SCRIPT_DIR/ios/Flutter/Secrets.xcconfig"

# --- Yandex MapKit API Key (injected into Info.plist via xcconfig) ---
YANDEX_MAPKIT_API_KEY="f050e8e3-a26c-404d-bf1d-2f07aa0c4e4a"

# --- Create Secrets.xcconfig if missing ---
if [ ! -f "$SECRETS_FILE" ]; then
  echo "Creating Secrets.xcconfig..."
  cat > "$SECRETS_FILE" << EOF
// Auto-generated by build_ios.sh — do NOT commit
YANDEX_MAPKIT_API_KEY=$YANDEX_MAPKIT_API_KEY
EOF
  echo "Created: $SECRETS_FILE"
else
  echo "Secrets.xcconfig already exists, skipping creation."
fi

# --- Ensure Release.xcconfig has correct includes (no optional '?') ---
RELEASE_XCCONFIG="$SCRIPT_DIR/ios/Flutter/Release.xcconfig"
if grep -q '#include?' "$RELEASE_XCCONFIG" 2>/dev/null; then
  echo "Fixing Release.xcconfig includes (removing '?' optional markers)..."
  sed -i '' 's/#include?/#include/g' "$RELEASE_XCCONFIG"
fi

DEBUG_XCCONFIG="$SCRIPT_DIR/ios/Flutter/Debug.xcconfig"
if grep -q '#include?' "$DEBUG_XCCONFIG" 2>/dev/null; then
  echo "Fixing Debug.xcconfig includes (removing '?' optional markers)..."
  sed -i '' 's/#include?/#include/g' "$DEBUG_XCCONFIG"
fi

# --- Build ---
echo "Building iOS release..."
cd "$SCRIPT_DIR"
flutter build ios \
  --dart-define=YANDEX_CLIENT_ID=bad2912d12db4c59a71511239a68c564

echo ""
echo "Build complete! Next steps:"
echo "  1. Open Xcode: ios/Runner.xcworkspace"
echo "  2. Product → Archive"
echo "  3. Distribute App → App Store Connect"
