#!/bin/bash
# Build iOS for TestFlight
# Usage: ./build_ios.sh [build-number]
# Example: ./build_ios.sh 25
# Then: Xcode Organizer → Distribute App → App Store Connect

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SECRETS_FILE="$SCRIPT_DIR/ios/Flutter/Secrets.xcconfig"

# --- Build number (optional argument, defaults to auto) ---
BUILD_NUMBER="${1:-}"
BUILD_NUMBER_FLAG=""
if [ -n "$BUILD_NUMBER" ]; then
  BUILD_NUMBER_FLAG="--build-number=$BUILD_NUMBER"
  echo "Build number: $BUILD_NUMBER"
fi

# --- Yandex MapKit API Key ---
YANDEX_MAPKIT_API_KEY="f050e8e3-a26c-404d-bf1d-2f07aa0c4e4a"

# --- Create Secrets.xcconfig if missing ---
if [ ! -f "$SECRETS_FILE" ]; then
  echo "Creating Secrets.xcconfig..."
  cat > "$SECRETS_FILE" << EOF
// Auto-generated by build_ios.sh — do NOT commit
YANDEX_MAPKIT_API_KEY=$YANDEX_MAPKIT_API_KEY
EOF
  echo "Created: $SECRETS_FILE"
else
  echo "Secrets.xcconfig exists, OK."
fi

# --- Ensure xcconfig includes are not optional (#include, not #include?) ---
for XCCONFIG in "$SCRIPT_DIR/ios/Flutter/Release.xcconfig" "$SCRIPT_DIR/ios/Flutter/Debug.xcconfig"; do
  if grep -q '#include?' "$XCCONFIG" 2>/dev/null; then
    echo "Fixing $(basename "$XCCONFIG"): removing optional '?' from includes..."
    sed -i '' 's/#include?/#include/g' "$XCCONFIG"
  fi
done

# --- Build IPA (works reliably; Xcode Archive has issues with YandexMapsMobile xcframework) ---
echo ""
echo "Building IPA..."
cd "$SCRIPT_DIR"
flutter build ipa \
  --dart-define=YANDEX_CLIENT_ID=bad2912d12db4c59a71511239a68c564 \
  $BUILD_NUMBER_FLAG

echo ""
echo "Build complete! Next steps:"
echo "  1. Open Xcode Organizer (Xcode → Window → Organizer)"
echo "  2. Select the latest archive"
echo "  3. Distribute App → App Store Connect"
