#!/bin/bash
# Build iOS for TestFlight
# Usage: ./build_ios.sh [build-number]
# Example: ./build_ios.sh 25
# Then: Xcode Organizer → Distribute App → App Store Connect
#
# КОНФИГУРАЦИЯ ВЫНЕСЕНА ИЗ СКРИПТА (артефакт-аудит 2026-09-01).
# Этот файл отслеживается git, а репозиторий публичный — значения конфигурации
# в нём быть не должно, независимо от того, секретны они или нет.
# Источники, в порядке приоритета:
#   1) переменные окружения YANDEX_MAPKIT_API_KEY / YANDEX_CLIENT_ID
#   2) mobile/android/local.properties (gitignored; оттуда же их читает Android —
#      см. android/app/build.gradle.kts, manifestPlaceholders)
#   3) ios/Flutter/Secrets.xcconfig (gitignored) — только для MapKit-ключа:
#      если файл уже есть, ключ берётся из него и пункты 1-2 для него не нужны
# Если значение не найдено нигде — скрипт останавливается ДО сборки и печатает,
# что именно дописать. Тихой сборки с пустым ключом не будет.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SECRETS_FILE="$SCRIPT_DIR/ios/Flutter/Secrets.xcconfig"
LOCAL_PROPS="$SCRIPT_DIR/android/local.properties"

# --- Читает ключ из local.properties (пусто, если файла или ключа нет) ---
read_local_prop() {
  [ -f "$LOCAL_PROPS" ] || return 0
  sed -n "s/^$1=//p" "$LOCAL_PROPS" | head -1 | tr -d '\r'
}

# --- Останавливается с внятным рецептом ---
die_missing() {
  echo ""
  echo "ОШИБКА: не найдено значение $1."
  echo ""
  echo "Дописать одной строкой в $LOCAL_PROPS:"
  echo "    $1=<значение>"
  echo "либо задать переменной окружения:"
  echo "    export $1=<значение>   # затем повторить запуск"
  echo ""
  echo "Значения — Yandex Developer Dashboard (MapKit-ключ) и кабинет Yandex OAuth"
  echo "(client ID). local.properties gitignored — в репозиторий они не попадут."
  echo ""
  exit 1
}

# --- Build number (optional argument, defaults to auto) ---
BUILD_NUMBER="${1:-}"
BUILD_NUMBER_FLAG=""
if [ -n "$BUILD_NUMBER" ]; then
  BUILD_NUMBER_FLAG="--build-number=$BUILD_NUMBER"
  echo "Build number: $BUILD_NUMBER"
fi

# --- Yandex OAuth client ID (нужен на КАЖДОЙ сборке) ---
# Не секрет: client ID виден в браузерной строке при авторизации. Вынесен сюда
# как конфигурация, а не как секрет. Секретом является client secret — на
# устройстве его нет вовсе (мобильный Yandex-поток implicit, см. OSB-M).
YANDEX_CLIENT_ID="${YANDEX_CLIENT_ID:-$(read_local_prop YANDEX_CLIENT_ID)}"
[ -n "$YANDEX_CLIENT_ID" ] || die_missing YANDEX_CLIENT_ID

# --- Secrets.xcconfig: создать, только если его нет ---
# Если файл уже есть (обычный случай на рабочем Mac) — MapKit-ключ берётся
# оттуда, и искать его в окружении не нужно.
if [ ! -f "$SECRETS_FILE" ]; then
  YANDEX_MAPKIT_API_KEY="${YANDEX_MAPKIT_API_KEY:-$(read_local_prop YANDEX_MAPKIT_API_KEY)}"
  [ -n "$YANDEX_MAPKIT_API_KEY" ] || die_missing YANDEX_MAPKIT_API_KEY

  echo "Creating Secrets.xcconfig..."
  cat > "$SECRETS_FILE" << EOF
// Auto-generated by build_ios.sh — do NOT commit
YANDEX_MAPKIT_API_KEY=$YANDEX_MAPKIT_API_KEY
EOF
  echo "Created: $SECRETS_FILE"
else
  echo "Secrets.xcconfig exists, OK."
fi

# --- Ensure xcconfig includes are not optional (#include, not #include?) ---
for XCCONFIG in "$SCRIPT_DIR/ios/Flutter/Release.xcconfig" "$SCRIPT_DIR/ios/Flutter/Debug.xcconfig"; do
  if grep -q '#include?' "$XCCONFIG" 2>/dev/null; then
    echo "Fixing $(basename "$XCCONFIG"): removing optional '?' from includes..."
    sed -i '' 's/#include?/#include/g' "$XCCONFIG"
  fi
done

# --- Bundle ID: проверка перед сборкой (артефакт-аудит 2026-09-01) ---
# MapKit-ключ ограничен по идентификатору приложения (com.nirivio.app) в Yandex
# Console. Сборка с шаблонным com.example.* пройдёт успешно, но карта в ней
# молча не заработает — ключ будет отвергнут по ограничению. В репозитории
# project.pbxproj до сих пор несёт шаблонное значение: правка делается на Mac
# (там же живёт DEVELOPMENT_TEAM, которого в репозитории нет) и должна быть
# закоммичена, иначе сборка с чистого клона снова уедет на com.example.
PBXPROJ="$SCRIPT_DIR/ios/Runner.xcodeproj/project.pbxproj"
if grep -q "PRODUCT_BUNDLE_IDENTIFIER = com.example" "$PBXPROJ" 2>/dev/null; then
  echo ""
  echo "ВНИМАНИЕ: project.pbxproj несёт шаблонный bundle ID (com.example.*)."
  echo "MapKit-ключ ограничен на com.nirivio.app — карта в этой сборке не заработает."
  echo "Исправить в Xcode (Runner → Signing & Capabilities → Bundle Identifier)"
  echo "и ЗАКОММИТИТЬ project.pbxproj, иначе правка снова потеряется."
  echo ""
  read -r -p "Продолжить сборку всё равно? [y/N] " REPLY
  case "$REPLY" in [yY]*) ;; *) echo "Отменено."; exit 1 ;; esac
fi

# --- Build IPA (works reliably; Xcode Archive has issues with YandexMapsMobile xcframework) ---
echo ""
echo "Building IPA..."
cd "$SCRIPT_DIR"
flutter build ipa \
  --dart-define=YANDEX_CLIENT_ID="$YANDEX_CLIENT_ID" \
  $BUILD_NUMBER_FLAG

echo ""
echo "Build complete! Next steps:"
echo "  1. Open Xcode Organizer (Xcode → Window → Organizer)"
echo "  2. Select the latest archive"
echo "  3. Distribute App → App Store Connect"
