import { ImageResponse } from 'next/og';

import { colors } from '@/lib/tokens';

import { NIRIVIO_MARK_PNG, NIRIVIO_MARK_PX } from './_brand/nirivio-mark';

/**
 * `app/opengraph-image.tsx` — Brand-default OG image (Brief 5).
 *
 * Generated programmatically via Next 16 `ImageResponse` — this file
 * convention auto-attaches to `og:image` meta tags for ALL route segments
 * unless overridden by a more-specific `opengraph-image.tsx` further down
 * the route tree or by explicit `openGraph.images` in a child
 * `generateMetadata` return.
 *
 * Per Brief 5 OG strategy (b): one static brand card for non-detail pages
 * (home / city / catalog); detail page overrides with per-establishment
 * `primary_image_url` via its own `generateMetadata`. Twitter inherits this
 * image when `twitter-image` is absent (X spec).
 *
 * Mark: the NIRIVIO cockade — the same sign as the mobile splash, the app
 * icons and the browser tabs. `./_brand/nirivio-mark` is GENERATED by
 * `tools/brand/nirivio_mark.py` (surface `web`) straight from the splash
 * recipe in `mobile/lib/screens/splash/painters/cockade_painter.dart`, which
 * is the single source of the sign — nothing here re-draws it. Satori has no
 * reliable two-point radial gradient, which is why the sign arrives as a
 * raster; it arrives as base64 in a module rather than a .png next door
 * because `new URL('./x.png', import.meta.url)` resolves to a CLIENT asset
 * path under webpack and `fetch` cannot parse it (the build then fails
 * prerendering this very route). Regenerate with:
 *
 *     python tools/brand/nirivio_mark.py web
 *
 * The card's own composition — brand-orange ground, white wordmark — is
 * unchanged from Brief 5 and still the placeholder the scope note below
 * describes. Only the letter «N» is gone, replaced by the actual sign.
 *
 * Scope intent (Trunk locked): "программный brand-card (Nirivio wordmark на
 * brand-фоне) — НЕ полноценный template (это (c)/OG Polish). Заменяем
 * позже." A future OG Polish brief can replace this with a richer template
 * (per-page typography, accent shapes, hero photos, the splash's beige stage)
 * without disturbing the file-convention interface.
 *
 * Font note: Satori (the engine behind `ImageResponse`) defaults to a
 * generic sans-serif when no font is loaded. Loading project's Unbounded
 * font would require fetching the .ttf — deferred to OG Polish; the
 * default sans renders Latin "Nirivio" cleanly.
 *
 * Next.js Route Handler — cached at build time (no Request-time APIs used).
 */

export const alt = 'Nirivio — гид по ресторанам и кафе Беларуси';

export const size = {
  width: 1200,
  height: 630,
};

export const contentType = 'image/png';

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          background: colors.brand.DEFAULT,
          color: '#FFFFFF',
          fontFamily: 'sans-serif',
        }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element -- Satori renders a plain <img>; next/image does not exist inside ImageResponse */}
        <img
          src={NIRIVIO_MARK_PNG}
          alt=""
          width={NIRIVIO_MARK_PX}
          height={NIRIVIO_MARK_PX}
        />
        <div
          style={{
            fontSize: 128,
            fontWeight: 700,
            letterSpacing: '-4px',
            lineHeight: 1,
            marginTop: 24,
          }}
        >
          Nirivio
        </div>
        <div
          style={{
            fontSize: 34,
            marginTop: 22,
            opacity: 0.92,
          }}
        >
          Гид по ресторанам и кафе Беларуси
        </div>
      </div>
    ),
    {
      ...size,
    },
  );
}
